const PLAY = "PLAY";
const SET_PLAY_LIST = "SET_PLAY_LIST";
const CLEAR_PLAY_LIST = "CLEAR_PLAY_LIST";
const SET_PLAY_MODE = "SET_PLAY_MODE";
const CLEAR_PLAY_HISTORY = "CLEAR_PLAY_HISTORY";

export const ACTIONS = {
  PLAY,
  SET_PLAY_LIST,
  CLEAR_PLAY_LIST,
  SET_PLAY_MODE,
  CLEAR_PLAY_HISTORY,
};
